---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: flux-webhook
  namespace: flux-system
spec:
  endpoints:
    - dnsName: "flux-webhook.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["external.${SECRET_DOMAIN}"]
