apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:anxh6qG158puukaJLrITgXCZBKmjSmbvDON2UKRv8C4=,iv:TNTTpNiHsQ0GbR8nkq5pjnKeBu5CVIGGpVBQxqRlqs8=,tag:bN4rmRP0wysXiUfeWxMfdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYURpbWZVR1RDME94RGd1
            REg2NGNhUTZuOER4Rmlnbk12RGVOS2lEaGxvClVhVWdxeVBhd1hPeE16MUU2b2dj
            cmhOSHVGcVpPZUxob0MraFM4MkRPRFUKLS0tIHlNeXQvdmtIRDg5VXJFVkg4TmZZ
            bmFzL3UxVlR1TURzam9sdldhSVlzMXcKxlsOQld6t87lKaSa/cQCS8lZDkbxv510
            toYxIAoCZ9TTyC3qr3noHvyNgPLM+O/SpBuIVECnDlKtV2ZYqM81Rw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cmVRV3ZqTVlZTG1QVkJy
            V1pVc0lZRlowTFNtcEMrbEdNcVdUYUNLb3hFClFzUlRHWTNTSzVITVEycWdiOWVJ
            VVkxdFNVRnJhNXV3MXA3UUtjODhJZ1kKLS0tIDdEVkxGVUhxMmUzL0lBS1B6UjBR
            dnhNb2tKVXN5Sm1FOEJvT3hhWmUvZG8K8AMe8cN50B7OyVFVaCU3o/VQ5XehKcp8
            1chJwl4152IG4b4d63FE0LoG3SHe7d7q7KVQGD7JgvbR1UEt5IMQXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T14:06:10Z"
    mac: ENC[AES256_GCM,data:ommWhgT+YZqS0MELpArN4ZPGz32NWea/Du5C6gIwmaFtSiCqUk07vZhAItaO/0mEIx8xhT6mxHZv394Ovf3bYdgj55TX09e1AfX40mjRb+e4kzb+HXPvCe1WgJlEK3EB7tn1trBX0K8X7xUo0i6EfLqoVnbNzMKmlRxRSwIG50s=,iv:cYSKEkLjG/LKD6XRIwyOOCWyiWdIXOqOY1APo8ykB6U=,tag:Uma8HZD1teUfIeETmZUh6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
