---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: booklore
  namespace: media
spec:
  endpoints:
    - dnsName: "booklore.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["external.${SECRET_DOMAIN}"]
