---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: &namespace observability
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 8.16.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    config:
      modules:
        http_post_net_peer_count:
          prober: http
          timeout: 5s
          http:
            method: POST
            valid_http_versions: ["HTTP/1.1"]
            headers:
              Content-Type: application/json
            body: '{ "id": 1, "jsonrpc": "2.0", "method": "net_peerCount"}'
            follow_redirects: false
        http_post_net_version:
          prober: http
          timeout: 5s
          http:
            method: POST
            valid_http_versions: ["HTTP/1.1"]
            headers:
              Content-Type: application/json
            body: '{ "id": 1, "jsonrpc": "2.0", "method": "net_version"}'
            follow_redirects: false
    ingress:
      enabled: true
      className: internal
      hosts:
        - host: &host blackbox.${SECRET_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    serviceMonitor:
      selfMonitor:
        enabled: true
      enabled: true
      targets:
        - name: net-peer-count
          url: http://192.168.0.148:8545
          module: http_post_net_peer_count
        - name: net-version
          url: http://192.168.0.148:8545
          module: http_post_net_version
