---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app node-feature-discovery
  namespace: &namespace kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    worker:
      config:
        core:
          sources:
            - pci
            - system
            - usb
    prometheus:
      enable: true
