---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cilium
  namespace: &namespace kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.15.6
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    autoDirectNodeRoutes: true
    bgpControlPlane:
      enabled: true
    bpf:
      masquerade: false
    cluster:
      id: 2
      name: turing
    containerRuntime:
      integration: containerd
      socketPath: /var/run/k3s/containerd/containerd.sock
    endpointRoutes:
      enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          className: internal
          hosts:
            - "hubble.web3.wiki.br"
          tls:
            - hosts:
                - "hubble.web3.wiki.br"
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: "192.168.0.0/24"
    k8sServiceHost: 127.0.0.1
    k8sServicePort: 6444
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    l2announcements:
      enabled: true
    loadBalancer:
      algorithm: maglev
      mode: dsr
    localRedirectPolicy: true
    operator:
      replicas: 1
      rollOutPods: true
    routingMode: native
