---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns-multicluster-turing
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: coredns-multicluster-reader
rules:
  - apiGroups: [""]
    resources:
      - services
      - endpoints
      - namespaces
    verbs:
      - list
      - watch
      - get
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coredns-multicluster-turing-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coredns-multicluster-reader
subjects:
  - kind: ServiceAccount
    name: coredns-multicluster-turing
    namespace: kube-system
