---
# Area
- { name: "area/github",             color: "0e8a16" }
- { name: "area/kubernetes",         color: "0e8a16" }
- { name: "area/documentation",      color: "0e8a16" }
- { name: "area/flux",               color: "0e8a16" }
# Cluster
- { name: "cluster/raspberry",       color: "d4c5f9" }
- { name: "cluster/turing",          color: "d4c5f9" }
# App
- { name: "app/networking",          color: "1d76db" }
- { name: "app/media",               color: "1d76db" }
- { name: "app/observability",       color: "1d76db" }
# Renovate
- { name: "renovate/github-action",  color: "027fa0" }
- { name: "renovate/github-release", color: "027fa0" }
- { name: "renovate/helm",           color: "027fa0" }
# Semantic Type
- { name: "type/patch",              color: "ffec19" }
- { name: "type/minor",              color: "ff9800" }
- { name: "type/major",              color: "f6412d" }
- { name: "type/break",              color: "f6412d" }
- { name: "type/config",             color: "fbca04" }
- { name: "type/security",           color: "b60205" }
# Uncategorized
- { name: "hold/upstream",           color: "ee0701" }
