---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: &namespace longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      defaultClassReplicaCount: 2
      defaultNodeSelector:
        enable: true
        selector: "ssd"
    metrics:
      serviceMonitor:
        enabled: true
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Storage
        gethomepage.dev/icon: longhorn.png
        gethomepage.dev/name: Longhorn
      host: &host "longhorn.${SECRET_DOMAIN}"
      tls: true
    defaultSettings:
      backupTarget: "s3://longhorn-uncaring@s3.us-east-005.backblazeb2.com/"
      backupTargetCredentialSecret: "longhorn-backup"
      defaultReplicaCount: 2
    longhornManager:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoExecute
    longhornDriver:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoExecute
