---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage-remote
  namespace: default
  labels:
    app.kubernetes.io/name: homepage-remote
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage-remote
  labels:
    app.kubernetes.io/name: homepage-remote
rules:
  - apiGroups:
      - ""
    verbs:
      - get
      - list
    resources:
      - namespaces
      - pods
      - nodes
      - services
  - apiGroups:
      - extensions
      - networking.k8s.io
    verbs:
      - get
      - list
    resources:
      - ingresses
  - apiGroups:
      - metrics.k8s.io
    verbs:
      - get
      - list
    resources:
      - nodes
      - pods
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions/status
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage-remote
  labels:
    app.kubernetes.io/name: homepage-remote
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage-remote
subjects:
  - kind: ServiceAccount
    name: homepage-remote
    namespace: default
