---
apiVersion: v1
kind: Service
metadata:
  name: smtp-relay
  namespace: network
  annotations:
    service.cilium.io/global: "true"
    service.cilium.io/shared: "false"
spec:
  type: ClusterIP
  ports:
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP
