apiVersion: v1
kind: Secret
metadata:
    name: bookorbit-secret
    namespace: media
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:hGxsrV+E2KG4I44FtnxSsJ1gaF1oTaG0yHrYoiQsnG9kMTvar/TAIMEyAWpHMGnt,iv:TFbg0aQIQKKezkXIW0CH5bpaIu/2qz0mI43QFiqnRBw=,tag:7jkxqI+8q/9Gs6t9ZsKiHw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:7cL/T18WdWoT07ivKdznLdwZeEbwrtEzVaJeQmUZrj5oh90pgjEWeQZyncTRJmb1tO5qgkVF9j7FoHTxnxs8tg==,iv:KB6dOLjZWiWos4DVJFPncHZtfYw7dem6Bk4f6TDpvto=,tag:DhoM57wpphpW4jxOQ14+Zw==,type:str]
    PODCAST_ENCRYPTION_KEY: ENC[AES256_GCM,data:FgdyAZSbRcUN/KZdtWyp8B+XsQTE5beqKYoXS3RQU/LuKw3mBfKaKttIWxNP1+yO5sw8UlA6WBkQwfEILzbp8w==,iv:Eof1jXf5qNDA8S3pYlsvte9hRBgl9oc2wLq+F9Ze/FE=,tag:Grbb9DeaD0am0wab8Fpa4g==,type:str]
    SETUP_BOOTSTRAP_TOKEN: ENC[AES256_GCM,data:keMK64NQS9a/p16mPiCaQRyVHcMwYW59A3VJzG1+uWk=,iv:F4VBWo2nLIbBcIoZaKz6qzuq02fYpEYBftvYBOo4KKo=,tag:MfdFnWTOzlNXqEFj15k8bw==,type:str]
    EMAIL_ENCRYPTION_KEY: ENC[AES256_GCM,data:rZVqfuFiwK3AEs9OvfbV9acz3vX9rF3sGsRo1GYWHbMHIS9hOE3DzAnqzTlaoDcVUHZslwGmy2TsWzzRpoAlvA==,iv:FUmsVV0PCFT8QmlR8/YA/FQkD9BurCzU7CzUYAC2yMw=,tag:dKK4f067vSSraFvzM5QmDQ==,type:str]
    BOOK_REQUEST_ENCRYPTION_KEY: ENC[AES256_GCM,data:GTdsZPSkH46RURrsqmEB7UK5l2qWUpJ+q95iZGDFmSTN5z1nodm4vdiBUawAM3q4ndSorEY6iWjJBi8T+xGsiQ==,iv:1sgSKBxFEL5I6DANdZjj+Gknl2KXsVRej1uUanhufhg=,tag:Mf6t78Qtw37h1sngq06gew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndDAvbEVqNGliUlN5dVdQ
            OE93NjJZbFExSW5wZThpdmlZWG91WmNwSTFZCk8vcTlCazAvVHp4Mi8yK0FrMU5x
            MWNBOEYwb2l4Szh1VUdMd3VmT3ZhWFUKLS0tIGdLVnhDREZ1S2k0TTNYMStqR2JW
            Q2FIWTRqL3A3clhobmlMMkVaelBqQjgKe1MVcQGW3ez+6aAuIlHkytO+FSRiihBa
            Dex9u4kUs4ov3+YwpsX/ylxLfDxuOG2UHgsUdQQUxaZDYJglTXfC2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cmJZaUpRQWhDSkNXcmUw
            UjF3YldTNHJWNlFpOFE2VFNSbVZZMXV2SUJrCmh0dnJwc0dQdjRGeE1pdVlGS2hV
            UUdRYWpJTjE2emVXYlk5ZW5TRlpqUjQKLS0tIHJnZXowMFptR3p5emozUHVWZjZi
            UWhUL3orcW82OVpyYzMyUUJGUGhnQ0UKCMKwUhv2Urmh+aZe6YWQpXH2PERDE1h0
            nkjGXmYgahXRGYAnc5L2uT811c5phlPwcBp8V4HwEcPkW+IiyFjkwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-26T15:16:51Z"
    mac: ENC[AES256_GCM,data:a5MOpZJ64SbBSZqFjdSgaOZrX9KsRyFqRh6dBZx8dRr6t4EzZH7Dj1fT7HINizPcDjLiipBwYgaSijZJd7uzDuHm4SUuljzt6vN8bLq5YfobEVF1n2/VzCA41SOPaLrhA5JClT9Rx/WAr6lOsFj0OYUtkfV+dNi3LM4XOItVJcI=,iv:zACXezcGoGZPirXgPPZglMj7OhKUynjiCurobnoUaXo=,tag:NacWLPvJMoPhaBTvZL1E8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
