---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./immich-charts.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./loki.yaml
  - ./longhorn.yaml
  - ./metrics-server.yaml
  - ./prometheus-community-charts.yaml
  - ./stakater.yaml
