---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
  - upstream.yaml
patches:
  - target:
      kind: ClusterRoleBinding
      name: local-path-provisioner-bind
    patch: |
      - op: replace
        path: /subjects/0/namespace
        value: storage
