---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.1.0/charts/other/app-template/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app jellyfin
  namespace: &namespace media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      jellyfin:
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 44
              - 109
        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: "10.8.13-1"
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 50000000
              JELLYFIN_CACHE_DIR: /cache
              TZ: ${TIMEZONE}
            resources:
              requests:
                memory: 1Gi
              limits:
                memory: 2Gi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
    service:
      main:
        controller: jellyfin
        ports:
          http:
            port: *port
          discovery:
            enabled: true
            port: 7359
            protocol: UDP
          dlna:
            enabled: true
            port: 1900
            protocol: UDP
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host jellyfin.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /cache
      movies:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: /movies
        globalMounts:
          - path: /media/movies
      transcode:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /transcodes
