apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: sonarr-secret
    namespace: media
    creationTimestamp: "2024-05-10T16:06:05Z"
    uid: 84ab9191-e827-4e3a-906b-ccc231b3e56e
data:
    api_key: ENC[AES256_GCM,data:PRCkkMnYvTdY8sUdFrXQu83PzoxT0kbv9M6H/PWONfXYAWgas/5kVBBX+Oc=,iv:6Gg9TckYCamo7WKtzUEpURSgmaC5xAtMAdPmD0+Ki+w=,tag:M2tsG3v3ystVEeyc53cV7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ary36xtm566uptguuhsj7xmuqzyz06ce54tcf6p3mge2thphqfs3gln40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVGtTNGh0cHcyRlY3cXU5
            UG1KcTFwWTVPS25sVVJIakFIcDJ6dWRZUlVRCnBPNmlOemVsVUNpaXdNOTllUklo
            Ny9qN3NuenVxeDEwd1V5eWw1L053akkKLS0tIEdRQWVYaHJhZFQyQS9jU25ZdTZp
            K0NmWnlYbGtZTEdwcDFmVkI1cmxXRzAK+eqe9aCy3loNu+WMpoZ3gPQ6+7B/7d9O
            jmxMtGVgm2bi3KxZGENJW/lBddCaO+AvVNv9lDXiHMYu8Ivm+wGe3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-10T16:10:27Z"
    mac: ENC[AES256_GCM,data:t0EOKY2SaMMyDTf0nePEIYNXIjPTARiw6CjoWNh6NSY5hhT2LDJ28GSuxGD6wkDpwBt8FlXP2YJWYnCTac1iqS58W+5Glq90UXH7Qe5OvcDsJP1OG5bMK3Kk/+WN0FzS9+Lxjikixofut2VE7sTNeradxcN/YN6hUjyaYLE0Mrw=,iv:8aJfXyKYiZT8ELKCzqA1AU3fsrfHa/VJX5c/8u0Amy8=,tag:Iv9V0CI/50b1mElqVNwYNA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
