---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: netbox
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.1.6@sha256:3edd4adb099cb5c3708c2cc182ec240e8209027dd2989a78bd6f9cf112ff652f
  url: oci://ghcr.io/netbox-community/netbox-chart/netbox
