---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: netbox
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 7.1.3@sha256:2d3098dd6aa506f016b2d4e7a24a8e8ea64d2820800310fe13d9b94c007481ed
  url: oci://ghcr.io/netbox-community/netbox-chart/netbox
