---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/ocirepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: netbox
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.0.46@sha256:09994049e4fdaee3fbbd607a939612f2ecdb5b932e85d22732d1b4112246df5f
  url: oci://ghcr.io/netbox-community/netbox-chart/netbox
