apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup
    namespace: storage
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RXDLzGBxQ19Xp9szzvzmM2H+pWGq3jvkhkxx4YE8FyTF9c1f,iv:aJrs6k10X1TwRczDiUkIO+qQL2MP6pqbD8qEpm1AYH0=,tag:zY0PDO2PxbKXWh4ht6zsjg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:LPgwNSfzf4YLBNv2+wleDCPFqZQO8qORL1Z6Yb+co9qWQEa1UEwO5X/04OsXWWPzprfzZg==,iv:HZyroUn4OCWkTydJzHKOpwBKZe1+wa3yr8gLNhfDOnY=,tag:RbQflJH9+htuo1boljLuyA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+52VDPkrc7CCg09TZzMcLMwOGJjHKU0kRN8VnJSF3Z174kUXPrfLBaSILU0=,iv:WbJH4/atLG4/i6VAZl07/xyqCUlz01mSUC87LnqGkME=,tag:R13SJUueh1Ez6J4iQ+3EWw==,type:str]
sops:
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeGVzNVFZcnNMcDhOc242
            WlRRODZGRVlQbmRCU0xqN2UwYVRUc0RPcTN3ClVGYkRDS1NpZ0Z3RGFSRURRc1BN
            OGtzZ2FFWlI2ZmZFQ0NLZXVENGpiazgKLS0tIElmaXNlb1NyZHlkYUwrMWxYRXdL
            SU80Z0VSVk14UTU4S1BuVmVEUFR1RGsKm9hSR+ipVR69uWtX51zJ9z/rlRH1cuIN
            FFToIeNJq4BgIMjcITBB7FBx2dapssIjJaP7JjqUssi3qOYmN5Vu6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbjQ3R0YveXVoOUhGcG1z
            b1NzbXVvckFFSG90K0E1QXMyRG9GalNHc2dzCnhCaGZaSHp6a09ST2pTNjhWMWIz
            QThybkp6NDFQZUpPc01vZFNFTElEK1UKLS0tIDNsZGlUb0d4Y2t0K3NzckVEYmlH
            WjA4RTQwLzQzV3BwbkVlYUNYK3dkV0kKGMw0rs+O2TwOe6vRay2eXDKBSTb5vtXi
            BC+8EVr3O84HyeWBSD0Vta5rkK8CG5ptPou9bJabehf4O2Lv3XzmIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T15:49:49Z"
    mac: ENC[AES256_GCM,data:MbnvXrg8l2xb2a5WuvkIi5RtVzrA5p6ndHiGXo3n8HvNqUG3MvNIq7EnUbs3yxAdsfJWvEUxb4bwGCaRtOMQfQbzuAQ7zRs9Fhnm9E01Kay77aJp++DGzxjfAoWYAnLXRKzSAnzGjlLTmISaa8OHfMA39bKh4ueh7tntDycdG9o=,iv:w5VMjVWtsfsjL2tQCKx/wqhKriDvvuQgD19qlzoI0Ak=,tag:xuUzeNJ0CvWGUzGViWUUMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
