apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup
    namespace: storage
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RXDLzGBxQ19Xp9szzvzmM2H+pWGq3jvkhkxx4YE8FyTF9c1f,iv:aJrs6k10X1TwRczDiUkIO+qQL2MP6pqbD8qEpm1AYH0=,tag:zY0PDO2PxbKXWh4ht6zsjg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:qsU4yXSwEIhTvFrEuBwjKHPSp+M4Y4gw3aswST4UrRYULxFJlXJTvg==,iv:ftQ/XV2SARQCU8rLL6Nh1j4Dy7w+OfdLpSgsaeyonss=,tag:xeK7eto4ks+jxUTbeNSbXw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+52VDPkrc7CCg09TZzMcLMwOGJjHKU0kRN8VnJSF3Z174kUXPrfLBaSILU0=,iv:WbJH4/atLG4/i6VAZl07/xyqCUlz01mSUC87LnqGkME=,tag:R13SJUueh1Ez6J4iQ+3EWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeGVzNVFZcnNMcDhOc242
            WlRRODZGRVlQbmRCU0xqN2UwYVRUc0RPcTN3ClVGYkRDS1NpZ0Z3RGFSRURRc1BN
            OGtzZ2FFWlI2ZmZFQ0NLZXVENGpiazgKLS0tIElmaXNlb1NyZHlkYUwrMWxYRXdL
            SU80Z0VSVk14UTU4S1BuVmVEUFR1RGsKm9hSR+ipVR69uWtX51zJ9z/rlRH1cuIN
            FFToIeNJq4BgIMjcITBB7FBx2dapssIjJaP7JjqUssi3qOYmN5Vu6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNbjQ3R0YveXVoOUhGcG1z
            b1NzbXVvckFFSG90K0E1QXMyRG9GalNHc2dzCnhCaGZaSHp6a09ST2pTNjhWMWIz
            QThybkp6NDFQZUpPc01vZFNFTElEK1UKLS0tIDNsZGlUb0d4Y2t0K3NzckVEYmlH
            WjA4RTQwLzQzV3BwbkVlYUNYK3dkV0kKGMw0rs+O2TwOe6vRay2eXDKBSTb5vtXi
            BC+8EVr3O84HyeWBSD0Vta5rkK8CG5ptPou9bJabehf4O2Lv3XzmIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T10:49:03Z"
    mac: ENC[AES256_GCM,data:+JvDmI0Fa7rU8vWcurBtNhxzcE58NhWX3A/0fgp5e0Zx2KyYVobACJcuem9dvL1NEWVtZRIgoFl9hxM5Xl24YNtbeyI703jHYKs8RnIXMXI1Au8OAVX/ouMH6pAajzSwNAl23YyFDr9Gu8A8jXomseBlGXE3ElE7Rq7+t7njd9c=,iv:8aIWnP3UaeCfU1Jv2E+Og2rl/rFqfzI4ius0xxHqGaM=,tag:xMj+wUfcCTJeK3M9D9/nBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
