apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: media
type: Opaque
data:
    OPENVPN_USER: ENC[AES256_GCM,data:HNGNkhQZ3M6QBhYobO4xkVgr50qDPoIvdPXVWjDKNwI=,iv:7x2bQkzpe4DMVhrCICU3k2oIwnzT+HApMgVcvPJLzgo=,tag:wC1I+KyPUg4FF4nJ0MajhA==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:7f979TM15JeLnAE5ULu5/QH+SNF4+wWXLf2hWQNSizc=,iv:27CQ1ul2xtHOaQIuwbkycdq7fLPeXphm6k9XtDcX8FE=,tag:l0mk8DQpT7XZnq0cUXGaeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ary36xtm566uptguuhsj7xmuqzyz06ce54tcf6p3mge2thphqfs3gln40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTDFibUdsTm1wcGo0K28v
            TmY2WW1VT2lRTmRzSjVNc0JGS01IdElQYmh3CjJOMm9OaWhSdWdpS0g2QzVUenFW
            TGdaN0d6WHFlREMzTXN3WklzT3FKNWsKLS0tIFpYRG1aYkJLZ0JuVnZvVHZXVm9N
            VVpvRURjRy9vRnNlM2FpeFRhcnNLQ0kKQS07UEDVbd/O3xFudxAqY8Ie49WT3tH+
            7/1kbNFdJza+KsyS67KM6ihITMCDNrytkcCf2KuXMnbvMX2Kfp6lDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-09T13:54:30Z"
    mac: ENC[AES256_GCM,data:JnxMnK9VL0B0ZExSIqA27gWt8eUP4Zrwj4PHNZ6aPnYNIgwIr5HmJIGLlFntjAphyh5Nnp24Lrk4MzFQWW4zAcFkwBceWJmuWWuM43NpP0DXEWSeEqfPlsJiBLSAdKcOIsI0RmIT7yFsYuJK0Ap8bCZTRWRo0RN+LTeM8L7T4Yk=,iv:0DH6toYp1rzVjvXxZXyovN7NEwi/exxPj9e5v997I1w=,tag:fCAmvtHnrfM6s2WSgS2mkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
