apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    HEALTHCHECKS_IO_URL: ENC[AES256_GCM,data:3L35bhA5mkb7s2l5jgKSAQSrx2hLd3WM4LOWUMh4bIzyCsZv8BV+BdGNtBTOyNpG64umrGFquvo=,iv:ay7gw62DgrMZcnkp2bA3IigNke/uAq6u5sY1uiZvD1k=,tag:Yneky4cKZ/KCeaiiyLQr3w==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:UYI7A4cnoMW6LB2u2rk=,iv:GRKlSB4W1GHTRXkA9fyTWqJZcjbFJVPgaWIZjxPlgvM=,tag:m1Gb/OGgFCI3KYm2YJ7jUQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:yxxmAaiQIgNNKuTP,iv:ijCjY0DZPDt2u/gjMxQ91V+a3okd/7J5rmSNqaABawM=,tag:1cEBaYTiQMxF6sJd1dSpWw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:NROOEvv2p/BqnKG5OVYv,iv:tLsrO8xW4rTEdaHm9bE60w1+pVtlQkmh3nfkOa6TK4Y=,tag:cY3VDLexaCOqwBZ+7hbM6g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:n91Brd4fEXGq0JhoHOBOOj6EAoRkVqk4w1VoqM/JUHOO8hgN,iv:ssaWwZdr9efj5TBQ6XB8TVbpSABlXqDQMC0sp8k1eAk=,tag:hJMlfE/ZJ6opKUbx6I6SIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UjVQcC9QMTFOV0pxSWRy
            YzZPYVZvZGtwMUtXT2dGSW1MUUxXMnZyNHdJCmgxc3M1Z25ldmc0V3F2cG9DSHp5
            ajkwblhIeVNHd01VMzZQeDhVRFdsL0EKLS0tIGsyTjFSQXBvdmJrODNGRjk2cXli
            R0RacFZvLzBnUkhvUzJCMTZUd3M1bDQKmHqDRkTzwNVwwSqBdHJoDAZ0256fLMuF
            Xnhyp3qLpz1RP6MylZnQwTmsZBVvQFi6gac7Yu7jEGEyJJQ384IqEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Uk1TZTV1N3l4SW5oYUZr
            ckwrY0Y0M05JK2piSDV5R1dIb1BBamJqbHgwCmlrSVY4V3kwSTI0RVlSQWNwR2Mv
            UjFKQUpneVZ6cDN5eURleG5Oa0N2WHcKLS0tIG5rNExDdHNYR3BoeDh6M2VOWEJU
            Tys4alpFdlVHZVBqeEIxaHgyTXJrSlEKayFLG7MILTO8Dapjn90S0pvFYDmSvlPQ
            hVPLuWEwNNNVSfuRLPkQi3spegTCeyos3k+e0OQmdU1h1+W8CON/6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-30T17:58:47Z"
    mac: ENC[AES256_GCM,data:mH1ZEOGVEFjah34T3iwfxxCKSz+4L2Jp6s1XSezB8K+QeDE7jk6KrOkdfDkQVxZJf7zaYOXOOwbfuaTrJDF8vdwddUiXBYrr6KOrsbmzxrzzRybDIIRoxjf40AQyvA/PjZjm8ra2A+uX8x3Y2eLcrt+3Vk3CiMPT/9kwsCZZ1PQ=,iv:i+tGgp9x/ju6bdNJnnk9Q+cr9ow/KY0xELlvpmNMMhc=,tag:ZuDEjopzIbO1cd1EL5w/wA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
