---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_CIDR: "10.69.0.0/16"
  NFS_SERVER: "192.168.0.173"
  NODE_CIDR: "192.168.0.0/24"
  TIMEZONE: "Europe/Stockholm"
