apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "1h"
    fluxcd.controlplane.io/reconcileTimeout: "3m"
spec:
  distribution:
    version: "2.5.x"
    registry: "ghcr.io/fluxcd"
  components:
    - helm-controller
    - image-automation-controller
    - image-reflector-controller
    - kustomize-controller
    - notification-controller
    - source-controller
  cluster:
    type: kubernetes
    multitenant: true
    networkPolicy: true
    domain: "cluster.local"
  sync:
    kind: GitRepository
    url: "ssh://git@github.com:22/willianpaixao/homelab.git"
    ref: "refs/heads/main"
    path: "kubernetes/raspberry"
    pullSecret: "github-deploy-key"
  kustomize:
    patches:
      - patch: |
          - op: add
            path: /spec/decryption
            value:
              provider: sops
              secretRef:
                name: sops-age
        target:
          kind: Kustomization
