---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app flux-operator
  namespace: &namespace flux-system
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: flux-operator
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: flux-operator
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
