---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-secrets.sops.yaml
  - cluster-settings.yaml
  - flux.yaml
  - github-deploy-key.sops.yaml
  - helmrelease.yaml
  - sops-age.sops.yaml
  - ./webhook/ks.yaml
