---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-secrets.sops.yaml
  - cluster-settings.yaml
  - github-deploy-key.sops.yaml
  - gotk-components.yaml
  - gotk-sync.yaml
  - pgp-public-keys.yaml
  - sops-age.sops.yaml
  - ./webhook/ks.yaml
