---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: reth
  namespace: observability
spec:
  staticConfigs:
    - labels:
        job: reth
      targets:
        - 192.168.0.150:9001
  metricsPath: /
