---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: &namespace longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: 1.6.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      defaultClassReplicaCount: 2
      defaultNodeSelector:
        enable: true
        selector: "ssd"
    metrics:
      serviceMonitor:
        enabled: true
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: basic-auth
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Storage
        gethomepage.dev/icon: longhorn.png
        gethomepage.dev/name: Longhorn
      host: &host "longhorn.${SECRET_DOMAIN}"
      tls: true
    defaultSettings:
      backupTarget: "nfs://${NFS_SERVER}:/longhorn"
