---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ocis
spec:
  interval: 1h
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      ocis:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init-config:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.2.0
            command:
              - /bin/sh
              - -c
            args:
              - |
                if [ ! -f /etc/ocis/ocis.yaml ]; then ocis init; else exit 0; fi
            env:
              OCIS_INSECURE: true
        containers:
          ocis:
            image:
              repository: docker.io/owncloud/ocis
              tag: 7.2.0
            env:
              DEMO_USERS: false
              OCIS_JWT_SECRET: "qwerty"
              OCIS_LOG_COLOR: true
              OCIS_LOG_LEVEL: info
              OCIS_LOG_PRETTY: true
              OCIS_URL: https://drive.${SECRET_DOMAIN}
              PROXY_TLS: false
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 1024Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      app:
        controller: ocis
        ports:
          http:
            port: 9200
    ingress:
      internal:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: owncloud.png
          gethomepage.dev/name: Owncloud
        hosts:
          - host: drive.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - drive.${SECRET_DOMAIN}
      external:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: drive.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - drive.${SECRET_DOMAIN}
    persistence:
      config:
        type: configMap
        name: ocis
        globalMounts:
          - path: /etc/ocis/web.yaml
            subPath: web.yaml
            readOnly: true
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        globalMounts:
          - path: /var/lib/ocis
            subPath: data
          - path: /etc/ocis
            subPath: config
      movies:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: /movies
        advancedMounts:
          ocis:
            app:
              - path: /media/movies
      series:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: /series
        advancedMounts:
          ocis:
            app:
              - path: /media/series
      tmpfs:
        type: emptyDir
        advancedMounts:
          ocis:
            app:
              - path: /tmp
                subPath: tmp
