---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: ocis
    files:
      - web.yaml=./config/web.yaml
generatorOptions:
  disableNameSuffixHash: true
