apiVersion: v1
kind: ConfigMap
metadata:
  name: ocis-config
  namespace: maedia
data:
  web.yaml: |
    ---
    web:
      config:
        apps:
          - files
          - search
          - pdf-viewer
          - admin-settings
