---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app immich
  namespace: &namespace media
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: immich-charts
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    postgresql:
      enabled: true
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-nfs
    server:
      ingress:
        main:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: &host immich.${SECRET_DOMAIN}
              paths:
                - path: /
                  service:
                    identifier: server
                    port: http
          tls:
            - hosts:
                - *host
