---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app immich
  namespace: &namespace media
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: immich-charts
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    postgresql:
      enabled: true
    redis:
      enabled: true
      architecture: standalone
      master:
        persistence:
          enabled: false
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-nfs
    server:
      ingress:
        main:
          enabled: true
          className: external
          annotations:
            external-dns.alpha.kubernetes.io/target: "photos.${SECRET_DOMAIN}"
            gethomepage.dev/enabled: "true"
            gethomepage.dev/group: Home
            gethomepage.dev/icon: immich.png
            gethomepage.dev/name: Photos
          hosts:
            - host: photos.${SECRET_DOMAIN}
              paths:
                - path: /
                  service:
                    identifier: main
                    port: http
          tls:
            - hosts:
                - photos.${SECRET_DOMAIN}
