apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup
    namespace: storage
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:par/wpzBDTrd+2/worYglL1QfvvhRPRsXdtleeedOi89676M,iv:E8u1kzXfLrGPZlkwJt7prj+01EEgdPJwkvlhogJ6Kas=,tag:4564hG7kP/YV62oMpT/Leg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:umVSPhuU1Qtuk6McINPtvYxKEHJHayKZhGeZnFpUeADy7nMbcqTxl1d/qzlBHvISjDT8kg==,iv:PRUgbAsMHMvWO8rMZ3VH00kIqlFDmANpUv9m8UnbNnA=,tag:nRwd/q5vUAxONK2aiBUJdg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:lJC9+eB3U2ZOLaS8w3cke93SbiiJ1oDG0ghlTmBOp7Ap4LhARtZDGzY6W/c=,iv:2kZ/+ePo8X1O3gimQCt6oePj31KyJRPcz5pM0NCyouY=,tag:qezP8kes5c86xPX/tdYdqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOEd6UWhTKy9EaEZKS2Vy
            QVZDdlRmRFcyQUdnZlkwUjV2ZmU2eWN1cHljCkFuRVY5RG80YThRRVNQd1hrUFVD
            VTdMTjRiRlRZYUxYOVI3eDE2VWpnOHcKLS0tIEtUeHIvL05uNnQwUUxvT3hSR0lK
            NjZaZldSbm1NQjE4MDdkU0hmWTMrNGsKgNd/eZ1CKDXDJf8uQzZQ/aPbHRPA+J1n
            W2euiq8uuaMEA+7uu3WY3BWw/0p5W2G6pQOVqepQiR7BMaigQedFKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkbHFLeXJQbXYwR25aRWFK
            WnczN05RUS9WcW05MVV0T2hvSk9EWnNiYUYwCjNrei9PazVyTFh0ckJvU0VOdFla
            VXFNNXQ3VjZtS3dlK3oyVFpkMHVUYncKLS0tIG1UQlh5M0h0Q3MxbGY5K0tmNWY0
            aXphVm1vSmFtakpuc0xlbG11dmdoaHcKnCi+RAh/rKhBTs3dmDaAr3xBXirp8IpP
            ClU6xD5SqSlzdJNudvF7Ae7dg+Z8L75jc5AHsgIA8HJbYLodp5qeQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T09:33:03Z"
    mac: ENC[AES256_GCM,data:OH/bo8ta88M5QHH1uZdLRkRxJD6DI5C0JiCWDIciR5PWne1/nTgi3hAsfpDMEGNho+89y5lhF1ZZQ/UX6s25DspN+//OyF+5zmtwA+HD44Bd5bkJtxgejXenfS0SQZ8SvHsBZivBhjtNjhmmtIXN71ALswICfQb1BR5/jyq58eU=,iv:tNFlU0kun/pWR6ciH49mD4KAG9L4lepSV797AdQxqd0=,tag:BgGeF18ytmYVUEGu55YNpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
