---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
  namespace: network
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    provider:
      name: pihole
    extraArgs:
      - --ingress-class=internal
      - --pihole-server=http://192.168.0.8
      - --pihole-tls-skip-verify
    registry: noop
    domainFilters: ["web3.wiki.br"]
    env:
      - name: &name EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: &secret external-dns-secret
            key: pihole
    resources:
      requests:
        cpu: 30m
        memory: 128Mi
      limits:
        cpu: 30m
        memory: 128Mi
    serviceMonitor:
      enabled: true
