---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
  namespace: &namespace ollama
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
    controllers:
      ollama:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.3.13
            env:
              OLLAMA_MODELS: /models
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: false
      ui:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: "0.3.35"
            env:
              DATA_DIR: /data
              OLLAMA_BASE_URL: http://ollama.ollama.svc.cluster.local:11434
              RAG_EMBEDDING_ENGINE: ollama
              WEBUI_NAME: Ollama
              WEBUI_URL: https://ollama.${SECRET_DOMAIN}
    service:
      ollama:
        controller: ollama
        ports:
          http:
            port: &port 11434
      ui:
        controller: ui
        ports:
          http:
            port: &port 8080
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: Ollama
          gethomepage.dev/group: AI
        hosts:
          - host: &host ollama.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: ui
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      models:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 64Gi
        advancedMounts:
          ollama:
            app:
              - path: /models
        labels:
          recurring-job-group.longhorn.io/backup: enabled
      ui:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 8Gi
        advancedMounts:
          ui:
            app:
              - path: /data
        labels:
          recurring-job-group.longhorn.io/backup: enabled
