---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
  namespace: &namespace ollama
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: DoesNotExist
    controllers:
      ollama:
        type: deployment
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.3.13
            env:
              OLLAMA_MODELS: /models
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
              TZ: ${TIMEZONE}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: false
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 11434
    persistence:
      models:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 64Gi
        advancedMounts:
          ollama:
            app:
              - path: /models
        labels:
          recurring-job-group.longhorn.io/backup: enabled
