apiVersion: v1
kind: Secret
metadata:
    name: cross-seed-secret
    namespace: media
stringData:
    config.js: ENC[AES256_GCM,data:ISnaVLr832N2jyBflPAKOJ990d48UuMEV6G+eTfpmtj2cYVTnDD2XO2FQDhGOc83vcr5xuWKl3JR61WxWVkfF0Sh5DtBQL1+Zcd6mHQy6Dc9dUUPjwyvglRO8u2XXaDJXbHUGteyct8YBK7wRWjWMe3aO90iXC+38Ndq4trkb5FmaZVg6kQP69RXYPdlxsCzQtlE0pHod1gBhDLu0ZuxofzZwr1RggoingvFDPwud6b5SuonBPO/mhBpA6PBOVaOvjD2SBAECfQKDxBfwfqMfBlcss/rHythfikU/VkxDLleO8YOxrAxE94Hz5edL0ZobYGVezjRYtK/K4AiMJqLH/k5dr2T0mzHmrf5f2UNyEwNVfQUXJ1wFiUyIMjOK2g95DR8SXYUkssHGDOHAtGKQJH4zlqPlXl4/iNDpiXqTsY1EUlkytit1yFTew2uXYg1rmKqUdsu5NssQZRat3/NEA7VIb0///8Z3mhHQLjnkYJ4g1y+DgNV0/78N3LwXG0Hue/I/cHMy9U54oNqqVpViB6am0shBdGJgOSPb51amiace+mmH5dvMRPCZakW/qeiahvEB3hhjqOGhL2VYKe6mT3Qaknj6/OqUmvnWfhBKrxj28xOhrYUioXOvti00DsclWeAImLBWuXkSKT0nLb/gZvUxttyLQzhq83LcMhNPvYixq+Si6KDpZoGH7Bd6VmNjhXlm0IpjrEU0yGNn2Op41vWnrfZVYWTnVcpCU28Y0NvXnIPhfPNsmEvtqEvse5F3uC7FINjZkNKWSAft4dl04dDUfU19Ewm6ddpbi4Zh1pSB/8imJ/fWvAz5nQarKznflqEaNHNuWRdtTw30IsHzoxqld61+pFuCLrxWEYxjf1K8q+rINfXenRQhlSS6H0JQUxEugE6GDv4gBWLOV/YxS81Q3sjJgbeFoqNrmFNF1SWu6i/kJ7khcR7raleQKAo2TNxYLJo0xn8oPXVT8csK01a2RgCGOn2x1v4MzLTkSnvZm4u6KpMwN5oOhwwmmmGC/XRUL1b/QblgzMXl7YZz5MFL62qgE82XSRlkdY5CTq5eCIkYZhrlpqg0DUoQYCqevBXMQyknzK2z5pjGZs1oIHN50TIL5GFYp/5vgxwUL4KUl2q027+WqMagv9B5Ygex5Jqy/eGPFD4OlkyQtpezSvdycmFQVr5+pnA1aBdJx1gzLXgzBczZCo8dc5t/xmVdZrrhxQw6pxAeRC8DE+n1DT8NIxhttST/VSj7dKX5NAJsCBHIspWFO0BuOE1c5lK+i1VviNX2WDQLGIy5mkAHQ9UDRYpXc5s0IhlUGsMJjwk0SqxHaxqLqgPU05/h84Wx4psCWQ0qggtUbUN1kDNGwI2Es8haxcByBk9OPRgyLOIN4+cLTvUxnpLL4Y18r+zAJDbj8WUU3zCGSgXUkgHtXQj/tccjQA4li6s85QI0I+J7RopfAMVnniDZhWuN3D1ayoZ6vn7r5QxVU2y6ZzORpr8YvVbh5kT+8BIspdcp9q+N97TkDesVdjybd3x30A0r8RVX2evc8lbL+diR7f4FauQCVW3KyGGwb7RO/ibHUxbzk7+MS6zXJlAYbM5JV0cNs1Ri+31LT36euD+TYb4ykmGjXj8mxEEPDDBqXXd7qTSKIAiqhbS9CBLCAq3ijvJlUyyY2YtUUpxpj5MqWA8V+KWkJCgtkORoEz2Z9yRqekR3ZuiAz8Szl3F/Pz54+mRXb8YhAZyxYQ3263ItnUDxieiBOolUJu1aVr27jcpRUFSDoiTpnFCoSy5mJ01PoED94KiOXK7JcBN/r3Bfj3Tat/B,iv:Z5JgEFFEOvTo2aHai3Tw4fMy5qGC8lWYhL2l6w9OX/0=,tag:riYT/o4AeXeJHbd2ggWPkg==,type:str]
sops:
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cDZ2d29tVFpIcjBLWnBT
            elYvNWIrMmY5MS9Nd0FCbDY4WkZ0bjFiNkYwCnFTQVhyejF4dTFQamdEVjV3dllY
            bEVaNFlXeThsUkJXMTdWZVAxM0NhVmcKLS0tIHgyem1zTm8xR3E3TXd1ZW1YZnpV
            VTN1d1JkZkJOWFZIN0RKQ1kweW9MZEEKOD3hAL94rI3yHZJCnvhVWL/P5rxnCnE0
            +2tIYrBtczBgTPonrcRTyO2+v1y2oW7Kvt8eb5ntacFD27GhyFXYoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SmFlSGlCd3pMcUdVeWVE
            QW51SG5IN3YvUlZoc3JUN0JRN0xPc3owOGdVCkF3SEFISUovaitBbVVxYS9kc2Jk
            S0N5Vi9vWnQ1M2tma213MDdUM3NmTTQKLS0tIGtUa3k4Y1FFZUZKdEwzTEZuRmh3
            T1lUK2JUeDN4VHZaMWlzUXlPL3NlblkK0VOZ5Qxn9tH3w8p2RjishA+AlUBCztw3
            Kjt6Y9CPdbxVICbw+pUYQzw0nM39inn+NiK2BqbtvkcMubGuhhl7QQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-05T13:16:44Z"
    mac: ENC[AES256_GCM,data:ZrTwSBOsm41UzhvmUEFCMf4DLeLqL8TanrvxCoVQ2mbAVA59QVzPSWOgTl8dNNrwQtTkh2r0pp1/odREKV1SmkHNeH4AxQ2tLtiI2R3uCbBAT8SPzc7SxU/A/U+pdUGoLHnSfBwczFSXIBD5OUibGMKaCesr1hZUMa3xmfoMito=,iv:0Y9teDaD3qAWS1wceBMagr2Uuq/FCjn+hD0xwtUaxug=,tag:h1WlY+I9LgiUnzeqcd5RwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
