---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app longhorn
  namespace: flux-system
spec:
  targetNamespace: &namespace storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/raspberry/storage/longhorn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 1h
  retryInterval: 5m
  timeout: 15m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app longhorn-recurring-jobs
  namespace: flux-system
spec:
  targetNamespace: &namespace storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: longhorn
  path: ./kubernetes/raspberry/storage/longhorn/recurring-job
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 1h
  retryInterval: 5m
  timeout: 15m
