---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app loki
  namespace: &namespace observability
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: loki
      version: 6.2.3
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    loki:
      commonConfig:
        replication_factor: 1
        schemaConfig:
          configs:
            - from: "2020-10-24"
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: index_
                period: 24h
      storage:
        type: 'filesystem'
      auth_enabled: false
    
    gateway:
      ingress:
        enabled: true
        hosts:
          - host: &host loki.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      resources:
        limits:
          cpu: 3
          memory: 4Gi
        requests:
          cpu: 2
          memory: 2Gi
      persistence:
        size: 32Gi
        storageClass: longhorn
      extraEnv:
        - name: GOMEMLIMIT
          value: 3750MiB

    memberlist:
      service:
        publishNotReadyAddresses: true

    chunksCache:
      enabled: false
    
    minio:
      enabled: false
    
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
    
