---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app knative-operator
  namespace: &namespace knative
spec:
  interval: 1h
  chart:
    spec:
      chart: knative-operator
      version: v1.18.1
      sourceRef:
        kind: HelmRepository
        name: knative-operator
        namespace: flux-system
  maxHistory: 3
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
