apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: network
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:yUlZ74TB3RnvWpPnmuSB/QRNKNoUOGIMkSsH1PJT/W6nLjmq,iv:0edF+ZmpcN2oKbX8YY71b2Xn3sqIyPD3l4u3HNeV7iQ=,tag:oDnqZ5GDOoTBo8HnpsNONg==,type:str]
    credentials.json: ENC[AES256_GCM,data:e6NLlw3P2RqOv8pmiIZdMLNkJCgbF+GD8t8nmhC1ai7ifMVANERHwWwFmbAbzFM0+nzOvMFIRvrYu2COiKs+oUxxad3hqVT4JnR1mAP6dnHAAPRPwU/9ZsqGRtTBS4//qCqozZQqEptE6kBgH7YwlcMiObL/suGLAkDEJeBlND4IT+AffuDV7VxdG1sKyOeEEQp9twDrjNgA6ieYOuU/gj7wEMwHFIyLrrRBrWnkOg==,iv:4djx3RsGMlRQyMoxITL1HBv4JV7bYSkqhEVNLTHObuA=,tag:6EPG5pZaVecwrRXaN+ahxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRUtvZXU5VzFLUzdWZG1M
            WHRoeTJMRmxwVVBHZTFSMHpjaDRIQ0tjMkQ4CldIUldIWTg1b2RDdVVtMWhrT1RE
            ZjZjbjQ4L09tV2FBRitvZjE4QmppK0UKLS0tIGxBNmRnQ2YxUUxXL3BCVnRWektL
            TTcvUEpFM3duRlFHOWJMQkNVZ05LNkEKkMGCKitgSPJQPAEDozQ9QeZKKhgNksyI
            qjVhDPEw9q2qeyriG8L3oS9FyJE/34G6hB30QfycaUOSgcayE5DS4Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVktlSHdVSGFSdVpuTFRi
            RjIxNEZvTDZiUXJONWZDd1FrVUtMV24yeUVRCk5jVmNWQ2VBSitINy9sMUVmMldP
            eXhmTGRTVkNHNC9xYy9MOUNiY2V2WlkKLS0tIDA4blB2QXIvT013cUR0UVg0T01Y
            b2tvcVd5WE1ZMHprTnJwMDliUXovTU0KvYvjdHxNOa+NVp+QZJjGRQUhK1vb11Nu
            oeTx83Ga/TA25+VjsK0O7J/Tzf6eA2Ibzg//A+5ejxFQu3+hiOQgzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T15:33:48Z"
    mac: ENC[AES256_GCM,data:OJQ+bpCCoW8p0mWk5jQkEgy0rfVtcj0VhLuavo0spwd64I9UOIYYmTA7Zh+WjR69ziU80/EUydyacSniIb6V2StwXmvQUmhAvtTkzE6lJc8+Deze2pevwOIYomABKp4iXdnaTt0jTFNks9d4RktgS90KJ5V4VyUQCLO171Loo+E=,iv:1ML7QUX4Y8ze3fgWw31dipOvawN5A1q1byiJZTKmaN0=,tag:Q/EPLftrqkFN0nKtFDRISA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
