---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: coredns
          volumeMounts:
            - name: multicluster-kubeconfigs
              mountPath: /etc/coredns/multicluster
              readOnly: true
      volumes:
        - name: multicluster-kubeconfigs
          projected:
            sources:
              - secret:
                  name: raspberry-kubeconfig
                  items:
                    - key: kubeconfig
                      path: raspberry.kubeconfig
