---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium/ks.yaml
  - coredns-custom.yaml
  - csi-driver-nfs/ks.yaml
  - metrics-server/ks.yaml
  - namespace.yaml
  - reloader/ks.yaml
