apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
    namespace: network
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:NxdVTY/TjpE5mkAg4CgtvA==,iv:gv2cVzLMUTO0Sm9sdc6uu8Nsuh6J+TmXMQDPXTZbYec=,tag:LwUuS7OBBQESWe1WZGY9wA==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:aJ34pRbtW1adTWQNcGsF,iv:YjtXlP+xF/QoKi1nY+O8mwrzxb3m6zdN772gRT7c5j0=,tag:ITp0xFxonBMqaKw0xWTzjg==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:teJMI5rO,iv:Cm+QE8ZkRzsho+m/ljFwyziKKUFko1rIaSX3gAdliEw=,tag:pA3GMm1BJ+y66dmhnyP2aw==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:z7QMtcFhwQuaEs6w74X84U3UH30V9lR28qpXcoRWYME1xTfF,iv:NR82C+nuPqCCyQEGCnKJWoQj8uIbLSKx9zj2HJrAnc8=,tag:cp9X0WH6jg4zaYBv05xB2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RDRNcVdycjNrYnlJcjJJ
            SEljQXg3ZVdWUCsrS1RLbHRhd2IzNHhIRVZvCklLZTBIWTJXQTdQR1I4cXlZRGVF
            dTZVeEhndEdDSnRLcmtnOXg0SjdaV3cKLS0tIGE5VEZ5bUZIeVBLeUZEWDNVVVFn
            N29OczkzeXlsR2VZajBrb3ZsTWwwZTgKENc84eHses6TsVA873Dhdg2RhS6wwNBQ
            AjPOI2Ro5NhBTdMHmIKMOam8p3VgbJDebb98gPoJ3ebFG+NCClqgRA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZjd5NmJWTjdKQXpsMDFF
            MjVMMkZrVW5aUUdma3Y0QlBQS0NKTHRoZWswCnJ0cTZJUVNkVktaYWJzVm80MFcz
            TTl2Z1VrbUNhUUVieXJ0UnJDVjdGSVUKLS0tIGpCUEl4cVRRK0pYbnJVbXZqRFNm
            dEpldjQvcG9LNSsxdnRnSWJRMmlTc28KR1a5Nx1hajO1iTV8OZ9V/8afvYrek6Be
            FfzjCgTy4ZgI9bAABUaVfuokxaAyzKztMUEBK9jjr1QJ4uaYC1JGIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-19T22:17:48Z"
    mac: ENC[AES256_GCM,data:V6l083J8mkPRhd5GXkjCNjiUrei81twftZULrGMd0jHTl/ae7EaaYcMsV2rSkyNtneWt2XTe5Tky3A4+7zDWSd5bNXW+W0OFAzrxu0CxQy39YbI/NI9aMnrrmfL8U7cpbWxtHnc5fmc0pCyVAXNLo7cFqwt1kTzYTbXn8IP6KQw=,iv:C+SIq1IXyYr40osQ5nRX1tiYBq6KD1WJ/LAuZwxjxkQ=,tag:AEdr4yv/6P7MKDGHZuvVcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
