---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
  name: radarr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
