apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
    namespace: media
data:
    api_key: ENC[AES256_GCM,data:sAZio1P7z+qD7PPciARJjOvNL2WuHULy7Us0lzP0UretgSl7LFhbwCKPJZM=,iv:pnNJNMvvzKocG5e0i/x43YQ0kwZUCqobVqjOq5IBmtw=,tag:zohS1uIUXB5CJ/k6/e1qfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsT09TTnpHT3dUT2wwNm9M
            MHYzd0JCSVhObGN6WERIUEJUS0lUN3o1S3pVClp2VjlYS3dqaXpxdmhlb0lkOUdj
            eEdpUnZNaS9ac2F1ZWJBdy9VcDNYdFkKLS0tICs3ckJjSFN1NFE1cWJtdkVxd2sw
            VCtmWk96b0JIWDdVV2lyZkd1Yk42WUkKUSwGWtL3JW+VW/c+4Sla/4LgI9AWOKma
            QBaYHSCh/+pQi3Q4JUxMSo+6QSCKfbVBFeb8xJDbawpqJkxjexFbtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cjFHUmpwYU1KbncrTUg3
            ek4rUldFSkhLQjQ0V2ZsckhGNGxjbnZqM0ZFCmRLNmdwZE9lUGdaWS9vU1dmUElL
            Wms3YU9BZ2tKdzg3cjJUTmNjSkJVKzAKLS0tIFF3dHRqaU1jenpPQ09RNVlPanVk
            SmFJYzFnUW9ORVFqaEpFMzFhZUs1SjAKBRHguKgGBEIvcovr31xvOUcH1GVzaSde
            etoBGCR2a9h7kYbSN/PMQzIx33jRZLsF1/Vxck8JUEbD0z7bCY066A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T21:51:47Z"
    mac: ENC[AES256_GCM,data:5kN0rpCz8QFIwRebqiHUjvwZMPRpKTQqokBfXruUauZ1v6iBl7yw9e66VL1dpuX3rQikg24l1Q7xTqQ3f8AGHCHSCAl4yMxrLpV2pAQ+u+0lvlh0DYINGYuNmEMcoDO9773jB98O3BF2jBd//CEJGk3/P/tPX4GSZW0VGAZfVQI=,iv:sGqGbuR4I+OLhJ3i/cpkfYlMwHShez4JgCF61rp1gEM=,tag:os3ulbeq0Vt7v4nJrjsx4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
