---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: immich
  namespace: immich
spec:
  endpoints:
    - dnsName: "immich.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["external.${SECRET_DOMAIN}"]
