---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: grafana
  namespace: flux-system
spec:
  type: grafana
  address: http://kube-prometheus-stack-grafana/api/annotations
  secretRef:
    name: grafana-token
