apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:vDtl9aw/yuMM2y7OrqGwElPTgwmZD/yQJd9TesRmRjYpuUtKirX66PIsyaoeBOCF36+mvBp/IKvrFlISsdpRdJioyt/wga7GgLw+0q2dMe1VF7qpAev3fwCzVGXWGQ==,iv:zt/HnoQE8OMAXgo6E7PHxe8qe1HgOlXxhPMxBIDSdNI=,tag:C6yP/bjsZYb3PwlAQEzkEQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZCP2ZOn/Y5GiYXPY,iv:hXAMqusNnnMZRHDFUD0RxaU0Cm+RBWyRbVWK5xfLtMw=,tag:Cl3d77A7nLBCw/xAFrDvQA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:g050DEtMvpnj+lMdSRwb,iv:YzTxGZQ1yOCL7erJhETdcT3LvAyo84zW1rq1EDXH7c8=,tag:62VxEcFZNJkf25Ij31cUHw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:TvKfU1dGHQhbFKHEuij0VcHyFDFo4B3mPn5NLPpXpFvml1UE,iv:SBhFB5hfTUlwQeiSEtht8EFyDuItJHzY3iVQ3rHqBE4=,tag:X/lEyi7sBIKKGdP4cJ+0gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ary36xtm566uptguuhsj7xmuqzyz06ce54tcf6p3mge2thphqfs3gln40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbnYzZnhLenMzUXBHMHI0
            SG5VNWRyS2hOWld1TDF6bEJGSlpuRFVLU2hBCm9PMk9QSDgyNHhLczVJR1NLdXh4
            QUp4MFc4V0prMzhMLzgySVFLUW1oR0UKLS0tIDErL21hOW5aQllNZDIyYTRXMzVZ
            MTZYajJ2ZnZVU2VHMFNIMEV5WGpHdEUK1Sl78NRaxF83Dx/qXGXKfcYM44aKrBAG
            4OiovcXaKnkWYJff9xzcIRI6zQMcqAPIVdOuG2KykUZ9jfTFkt+XFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T11:43:34Z"
    mac: ENC[AES256_GCM,data:1yFtvMP8yG3mAI7vzzhn/6KR6NZlJ9Cj0oYbS1ZGSz6/2z6TNwMNZC1WyCfX1diPsBZKjSmWt2sdVrtYc6vw17iPhdtcXTjg0drpymW70+GXy1ysPjpVopgiZUY6bRDS154VNL08GWNcYUEnJiY9vm9bdv1+prJaRqr4FdU4SI4=,iv:W1daZtAQ0JG+PObndxfht8bGaK43S+XiYkRAK6uA+7A=,tag:GyJImwuUJLVnp8e66A25ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
