---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app reloader
  namespace: &namespace kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: reloader
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    reloader:
      reloadStrategy: annotations
      readOnlyRootFileSystem: true
      podMonitor:
        enabled: true
        namespace: *namespace
      deployment:
        resources:
          limits:
            cpu: 15m
            memory: 64Mi
          requests:
            cpu: 15m
            memory: 64Mi
        containerSecurityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
