---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
  namespace: &namespace media
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: immich-charts
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    env:
      TZ: ${TIMEZONE}
    image:
      # renovate: datasource=github-releases depName=immich-app/immich
      tag: "v1.106.4"
    postgresql:
      enabled: true
    redis:
      enabled: true
      architecture: standalone
      master:
        persistence:
          enabled: false
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-nfs
    server:
      ingress:
        main:
          enabled: true
          ingressClassName: external
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: "photos.${SECRET_DOMAIN}"
              paths:
                - path: /
          tls:
            - hosts:
                - photos.${SECRET_DOMAIN}
        internal:
          enabled: true
          ingressClassName: internal
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            gethomepage.dev/enabled: "true"
            gethomepage.dev/group: Media
            gethomepage.dev/icon: immich.png
            gethomepage.dev/name: Immich
          hosts:
            - host: "immich.${SECRET_DOMAIN}"
              paths:
                - path: /
          tls:
            - hosts:
                - immich.${SECRET_DOMAIN}
    machine-learning:
      persistence:
        cache:
          type: pvc
