---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-nfs
  namespace: immich
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /photos
    server: 192.168.0.154
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-nfs
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Mi
