---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photos-nfs
  namespace: immich
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /photos
    server: 192.168.0.173
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos-nfs
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-cache
  namespace: immich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 32Gi
