---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app openspeedtest
  namespace: network
spec:
  interval: 1h
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      openspeedtest:
        containers:
          app:
            image:
              repository: openspeedtest/latest
              tag: v2.0.6@sha256:a6a7e3b3e9e93cfe7b9b2eb49c60b2a93644149a0a600845d4df57148b193ff6
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 3000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 20m
                memory: 256Mi
              limits:
                memory: 512Mi
    service:
      app:
        controller: openspeedtest
        ports:
          http:
            port: &port 3000
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Network
          gethomepage.dev/icon: openspeedtest.png
          gethomepage.dev/name: OpenSpeedTest
        hosts:
          - host: openspeedtest.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
