---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: controllers
  namespace: system-upgrade
spec:
  version: "${KUBE_VERSION}"
  upgrade:
    image: rancher/k3s-upgrade:v1.35.2-k3s1@sha256:ed1b539a6840468e9d386fbcc7830fa3ca9603de4c69c2b7c5b16f719bd1d41c
  serviceAccountName: system-upgrade
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
      operator: Exists
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
      operator: Exists
    - key: node-role.kubernetes.io/etcd
      effect: NoExecute
      operator: Exists
    - key: CriticalAddonsOnly
      operator: Exists
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: workers
  namespace: system-upgrade
spec:
  version: "${KUBE_VERSION}"
  serviceAccountName: system-upgrade
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  prepare:
    image: rancher/k3s-upgrade:v1.35.2-k3s1@sha256:ed1b539a6840468e9d386fbcc7830fa3ca9603de4c69c2b7c5b16f719bd1d41c
    args: ["prepare", "controllers"]
  drain:
    force: true
    skipWaitForDeleteTimeout: 60
  upgrade:
    image: rancher/k3s-upgrade:v1.35.2-k3s1@sha256:ed1b539a6840468e9d386fbcc7830fa3ca9603de4c69c2b7c5b16f719bd1d41c
