---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qbittorrent
  namespace: media
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: 6881
        - protocol: UDP
          port: 6881
  egress:
    - to: []
      ports:
        - protocol: UDP
          port: 51820
