---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: node-exporter
  namespace: observability
spec:
  staticConfigs:
    - labels:
        job: node-exporter
      targets:
        - 192.168.0.148:9100
        - 192.168.0.150:9100
    - labels:
        job: prysm
      targets:
        - 192.168.0.150:8080
        - 192.168.0.150:8081
  metricsPath: /metrics
