apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: gitea-runner-secret
    namespace: gitea
stringData:
    GITEA_RUNNER_REGISTRATION_TOKEN: ENC[AES256_GCM,data:YBCI/Rp8yOiE/PN6iRea/yPDDYIRTX6rTWEcLT2evKAALJB4K1b/Ww==,iv:X1BkiWTVbwMP3n/VvvPE6DzIFckywsRuzcI+4TT9K2o=,tag:A+HC5PO0OTcvnhTt+8BVRA==,type:str]
sops:
    age:
        - recipient: age1nkvss2a8xvmjauvr5mxzm233hyh2mk2fg4s6pt0t0kcn03dv34wqtgymg8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M2E4UERYYlkrZSsxWm1O
            MThKVmtFRllpcWhkem9RamQ3clhPUGJyTmxzCk43a3kwMzlCbEFsN3AyeTdzUCtO
            cDhBRlV0dFAwMmhDNjZZeTd3RHQ2WUkKLS0tIFVWSTZXRFZaTG5veDVtaDRXRWFm
            ZGE5anVSUDI5WUlPSndXV0k2Q09BRVkKfR1dtdONPLIK7DiLZaGGP+Lb6dISDS5Q
            JDl8OrWkgSDc4ob2nA/Qut/9ICwdGyp2lHzU2WigAe04r14HbW6Kkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wxwqdrmkwkzsxajp58g0cgeextgf4wq287fv82pptv9yghkfgcqql66zhj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZFpJaHlBNHVCYlExUlFP
            a3REb0JoUlYvLzBIRm1zU1Ywc2s4Nm5NNVFrCmtEZVhmWVhVeGFNUVNXcy9XV09h
            QUFvd0pXdnBhMXZxcWJISzZFVGZueEUKLS0tIDgzdXR3U1l5YjBvZ0d6Y3NWRldm
            TmRPYVIvc3N1d3hQaGdvNWhycEx3TE0KEBVv8wussL+9EC2SvsiqdA7+F23gGbzd
            EFKA3YBaMMV5iPBHEfM0zdjed/t/qasB7SWjxxSXksaZldXb0gZRGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-04T11:34:19Z"
    mac: ENC[AES256_GCM,data:SBjpTfy1JRtaawcC+QoZ2xDPHCTvdhEViDDPaxXdR6gSWKHIJWLQi9mJENbMyJCmvV/ZHDc5F+/pFITjcqUAl8DnTSYxD8CTRYfMv2d6P7aIYZdlS0ickqo79GT0awoUSmuWW0MoQeInxv90VMBvgypjT5sWquBAOqSfjOCA24k=,iv:N2EishRoJKuAePBGZsAJy8ZZx4/3SzsMfDSbC6hXVuY=,tag:qs7k0HGQP7QNUwQvBQmTJQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
