apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:OIxOogkOGxAu2ndiSKoVTU1tobhy9pDXynPtpHGEw54=,iv:Top94HSeWnztscQupIBrPVnuu+lWxun1UZUoY7G4Eow=,tag:1Ni2FZWbJNtGvRl6EQCwNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ary36xtm566uptguuhsj7xmuqzyz06ce54tcf6p3mge2thphqfs3gln40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLL3FkUm9OMGJLS1ZiRVFr
            VFBYR3FCZDkwTVRUWW9jZ1YzTmEvbkwzVzNnCkhPalpRN0JybjEvOUVoVHFTNnZ2
            TXRsSjdhRlQrVWUxUE8vSDRGMjA3RDAKLS0tIENxODhsWXUzdWNPc3U4TlQ4MXl1
            am11TUFYbUdKVVdEU05RRHg1OFFvWU0KvXrh/mQtb/HRESZFuj50MobN5e+J8Ck2
            5JWmngBltz3DtD1TS13pLnID/rPVqtPQXyVLGUMtwsvO+URUEYunLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T20:32:53Z"
    mac: ENC[AES256_GCM,data:Wd4G9lSrw8QvAjQ6mm2N2S2dp/gJNujaZQTGHH+IvGWAF7TadDNbx48G0H3QLbszuuAt0c+lg4eRDPe6Y3oXcIoIGq7RuvscqNAt02+xcAk6qj/mOI9vDn4mVxkbqMRXY/ihBvX3l4Txbpz3edPWLv8yEPkPfLdgDNs8ZpDE/oA=,iv:BVb1qk1LLWk9r3RUFbgrs6bQgL1j3KqhYBeNcVpgoOY=,tag:QZxwnbqW+YEvRpkO44/p5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
