apiVersion: v1
kind: Secret
metadata:
    name: pagerduty-config
    namespace: observability
data:
    serviceKey: ENC[AES256_GCM,data:/Sd+3uwWfTMVJuIbhukje2DFxFB2miMCgAAGTEaJ78tAXfNpI8tLvIo+16A=,iv:wb54aglzHP/dKqt/rVq+XNEgd/yVBv3RT8OW87A2dVI=,tag:XO9eNVdxOKW8mwWtcUEalw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ary36xtm566uptguuhsj7xmuqzyz06ce54tcf6p3mge2thphqfs3gln40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aEFCUEtlNUp6ZFpEVFZV
            aFRKQlRmcDBhbG5hbXZYdjVFVWkxMFd6MVU0CjV1RkNOT1hOdHQ5MWVCeGM4VDhZ
            WC96UnVyU2ZvV3VwN3pBVkczRzI1c0kKLS0tIDVySjZmMng4dERJUUJmbjNOTVdt
            OFd6L0NKRWhVZ1BtWGo0VHlKdTlzVVkKQurwFEB5NOeCCkOTJzKCpkcxx/VYvFD8
            g0n7DHT3D6cW222aELOloO6BonZBCxU8XAhrgijLNs2hOcl0v3uK/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-24T10:25:57Z"
    mac: ENC[AES256_GCM,data:mNTqA2F9cj5ksTrBuRLhR75OdP/EYxrHOB1Ke5qesMT6QsELz/vpLTexhFXc+dzJwww4CwTmEsqvZTJPXI1QWhCtXaOiMCx+rc76awPciO6uViE5UdM/KcxkzH42142VlQzxdjF4HjSP6FyRLu1XeveW0rXEcd1FtmuVfKVeVGU=,iv:vwrwyqhNySf4lBws5yAQRIxxSUcmh0MWdDo0StuXzlY=,tag:1zNzjkXiZ5PJ5JSQ7AUD9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
