---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app qbittorrent
  namespace: &namespace media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.0.8
        options:
          - name: ndots
            value: "2"
    controllers:
      qbittorrent:
        pod:
          nodeSelector:
            disktype: ssd
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.5@sha256:c019af23966ebafcaf1713d4553bc043246858b711a7d57d8bee358a89990a3e
            env:
              QBITTORRENT__PORT: &port 8080
              QBITTORRENT__BT_PORT: &bittorrentPort 0
              TZ: ${TIMEZONE}
              UMASK: "022"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                memory: 1Gi
              limits:
                memory: 4Gi
            securityContext:
              runAsUser: 2000
              runAsGroup: 2000
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: v3.38.0
            env:
              DOT: "off"
              DNS_ADDRESS: 1.1.1.1
              FIREWALL_INPUT_PORTS: 8080
              FIREWALL_OUTBOUND_SUBNETS: 10.69.0.0/16
              SERVER_CATEGORIES: P2P
              SERVER_COUNTRIES: Sweden
              VPN_SERVICE_PROVIDER: nordvpn
              VPN_TYPE: openvpn
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: qbittorrent.png
          gethomepage.dev/name: qBittorrent
        hosts:
          - host: &host qbittorrent.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        labels:
          recurring-job-group.longhorn.io/backup: enabled
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      movies:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: /movies
        advancedMounts:
          qbittorrent:
            app:
              - path: /media/movies
      series:
        enabled: true
        type: nfs
        server: ${NFS_SERVER}
        path: /series
        globalMounts:
          - path: /media/series
