apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: observability
  labels:
    alertmanagerConfig: kube-prometheus-stack
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'pagerduty'
  receivers:
    - name: pagerduty
      pagerdutyConfigs:
        - serviceKey:
            name: 'pagerduty-config'
            key: 'serviceKey'
