apiVersion: v1
kind: Secret
metadata:
    name: pagerduty-config
    namespace: observability
data:
    serviceKey: ENC[AES256_GCM,data:x1caQtz+ptwTVq5HdaGBZ2Cg8E2qaxpSByYYUbIKKZLLLgetwN+H3nsNR3k=,iv:9zxILCPahd12Zg2Vp+Q/QrFCy0kZdpg9eMb9pyCcMmU=,tag:NVf//ZPfN0rxKELzLjLvgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ary36xtm566uptguuhsj7xmuqzyz06ce54tcf6p3mge2thphqfs3gln40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aEFCUEtlNUp6ZFpEVFZV
            aFRKQlRmcDBhbG5hbXZYdjVFVWkxMFd6MVU0CjV1RkNOT1hOdHQ5MWVCeGM4VDhZ
            WC96UnVyU2ZvV3VwN3pBVkczRzI1c0kKLS0tIDVySjZmMng4dERJUUJmbjNOTVdt
            OFd6L0NKRWhVZ1BtWGo0VHlKdTlzVVkKQurwFEB5NOeCCkOTJzKCpkcxx/VYvFD8
            g0n7DHT3D6cW222aELOloO6BonZBCxU8XAhrgijLNs2hOcl0v3uK/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-24T09:52:06Z"
    mac: ENC[AES256_GCM,data:z5sS7oiWIeaijnDApG4UjFBvCeGpjmdBUFTKkVANccs2wQ1EoTaE93Cno8gpHQ6geIdb9ZNyPOlFBWwpQOlvFqH/0Jlb1bopo6J51hFBr3qZgb3wbkJR/UVGxg+jVZ6veocXoyiF4TayNWAafXNNG/qDjrid81URLO8p2LudFks=,iv:fuhzgDlofGST+99/DSrxg+8ALIg1iPQXZSYhBcJ6gkw=,tag:9o/nEcB9BerDcuH4OThevA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
