---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: backup-weekly
  namespace: longhorn-system
spec:
  cron: "0 2 * * 0"
  task: "backup"
  groups:
    - backup
  retain: 8
  concurrency: 1
