---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: snapshot
  namespace: longhorn-system
spec:
  cron: "0 2 * * *"
  task: "snapshot"
  groups:
    - backup
  retain: 7
  concurrency: 1
