---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: &namespace default
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      homepage:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.4.4@sha256:cd8da3c81ede2a072510930defdcf44c7a0473f72a6d5216beea3b13b3093afe
              pullPolicy: IfNotPresent
            env:
              HOMEPAGE_ALLOWED_HOSTS: ${SECRET_DOMAIN}
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: homepage-secret
            resources:
              requests:
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 256Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              fsGroup: 1000
              fsGroupChangePolicy: "OnRootMismatch"
              readOnlyRootFilesystem: true
              runAsGroup: 1000
              runAsNonRoot: true
              runAsUser: 1000
    serviceAccount:
      create: true
      name: homepage
    service:
      homepage:
        controller: homepage
        ports:
          http:
            port: 3000
    persistence:
      config:
        enabled: true
        type: configMap
        name: homepage-config
        globalMounts:
          - path: /app/config
      logs:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
    ingress:
      homepage:
        enabled: true
        className: internal
        hosts:
          - host: &host ${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: homepage
                  port: http
        tls:
          - hosts:
              - *host
