apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
rules:
  - apiGroups:
      - ""
    verbs:
      - get
      - list
    resources:
      - namespaces
      - pods
      - nodes
  - apiGroups:
      - extensions
      - networking.k8s.io
    verbs:
      - get
      - list
    resources:
      - ingresses
  - apiGroups:
      - metrics.k8s.io
    verbs:
      - get
      - list
    resources:
      - nodes
      - pods
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions/status
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: default
