---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: jellyfin-cross-cluster
  namespace: media
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "8096"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            io.cilium.k8s.policy.cluster: raspberry
            io.kubernetes.pod.namespace: kube-system
            k8s-app: cilium
      toPorts:
        - ports:
            - port: "8096"
              protocol: TCP
