---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: willian-eth
  namespace: default
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      main:
        strategy: RollingUpdate
        serviceAccount:
          create: false
          name: willian-eth
        containers:
          app:
            image:
              repository: ghcr.io/willianpaixao/willian.eth
              tag: sha-836c9f51ae8d7123e0bfd595ef534dd79c514f0c@sha256:4fcd9788c4587db4c383e1d0b403d29161b46206cc6df9efef639b16508084de
              pullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 50m
                memory: 64Mi
            probes:
              startup:
                enabled: true
              liveness:
                enabled: true
              readiness:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              privileged: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 101
              runAsGroup: 101
              serviceAccountName: willian-eth
    service:
      app:
        controller: main
        ports:
          http:
            port: &port 80
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host willian.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      tmp:
        enabled: true
        type: emptyDir
        advancedMounts:
          main:
            app:
              - path: /var/cache/nginx
                subPath: nginx-cache
              - path: /var/run
                subPath: nginx-pid
