apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:DA85ND2HyVCZ9FRUgVOs1J0xMqtqQYAaB99fUYSL0YsB6yo2lw==,iv:1pxO/cXjlEwfA0cQw/0gooMlRv6/5PHBT1s5vtzHn1A=,tag:vmqDLZ+i5VV0qcchKRO+4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17ary36xtm566uptguuhsj7xmuqzyz06ce54tcf6p3mge2thphqfs3gln40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSNmtLb21nNzEyQXBvdjRq
            ZSt4TnRJTFpNOW5vd2lBY2o5Sk5YZVpNQUE4CmVOaWlRTTRTWmlhdy9LdTlWK21J
            TUZRS21LenhwQjFvK0w3aDVnNTJCdTgKLS0tIFJGdFFscEN2TUoxblpyNWZjbGM4
            NzZHTjltUEptL3lnZVg4Vm1hL3o3aG8KcjKedh0A8vFl50ybQ8rjlrDpErhLnoW7
            34X2SZ4wLgoJrZpOTHwQGuBiktiXfHMKVhv1q1pcfRI6nx80gyEK1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T18:40:31Z"
    mac: ENC[AES256_GCM,data:+J4LU/nk6oKylTOCfmNeST50iQ0Q7xJ3JfswcBvQHWosqXb3AGGftFWJZ/pQoPDezZoCgmezEQrrwRfB/gviuwNWBiCxTaMWSwNHV2fu+TAY7PMony77mpwNd62g4bSayQQ96cfaG0xufMeO+GYvFBZ331HWMioldlDylbnHTqs=,iv:xwLXa4uvIRPcJRnTjwpo8IJ4WvG3Zjj8ZU77rxlGBWQ=,tag:3RXOOjepLLOR3V2fUA/CbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
