{
 "title": "Raspberry Pi",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(instance) (avg_over_time(node_hwmon_temp_celsius[5m]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg by(instance) (avg_over_time(node_hwmon_temp_celsius[10m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "avg by(instance) (node_cpu_scaling_frequency_hertz)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "avg_over_time(node_hwmon_curr_amps[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(node_hwmon_curr_amps[10m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "node_hwmon_pwm", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}