---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Kubeconform"

on:
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**"]
  workflow_dispatch:

env:
  KUBERNETES_DIR: ./kubernetes

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - uses: docker://ghcr.io/yannh/kubeconform:latest@sha256:faffaf43f95aa6425306e1ab8d6fcad72acb9049158f38e574c085ea1ec0f64e
        with:
          entrypoint: "/kubeconform"
          args: "-summary -output json -ignore-missing-schemas -ignore-filename-pattern json ${{ env.KUBERNETES_DIR }}"
